version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'

mkdocs:
  configuration: mkdocs.yml

# Dependencies required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
